name: Build and Deploy to Artifact Registry

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: musicmille
  IMAGE_NAME: musicmille_backend
  REGISTRY: europe-docker.pkg.dev
  REPOSITORY: docker-repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Authenticate to Google Cloud
    id: auth
    uses: google-github-actions/auth@v1
    with:
      credentials_json: ${{ secrets.GCP_SA_KEY }}
  
    - name: Authenticate to Google Cloud
    id: auth
    uses: google-github-actions/auth@v1
    with:
      credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker europe-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
        docker build \
          --build-arg SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }} \
          --build-arg SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }} \
          --build-arg SPOTIFY_USERNAME=${{ secrets.SPOTIFY_USERNAME }} \
          --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          --tag "$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}" \
          --tag "$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest" \
          .

    - name: Push Docker image
      run: |
        docker push "$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}"
        docker push "$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest"