name: Build and Deploy to Artifact Registry

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: musicmille
  IMAGE_NAME: musicmille_backend
  REGISTRY: europe-docker.pkg.dev
  REPOSITORY: docker-repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authorize Docker push
      run: |
        # Configure Docker to use gcloud credentials with Artifact Registry
        gcloud auth configure-docker europe-docker.pkg.dev --quiet
        
        # Add more detailed logging to debug the issue
        echo "Verifying authentication configuration..."
        gcloud auth list
        
        # Make the authentication call more explicit
        echo "Authenticating with Artifact Registry..."
        gcloud --quiet auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://europe-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build \
          --build-arg SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }} \
          --build-arg SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }} \
          --build-arg SPOTIFY_USERNAME=${{ secrets.SPOTIFY_USERNAME }} \
          --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          --tag "$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}" \
          --tag "$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest" \
          .

    - name: Push Docker image
      run: |
        docker push "$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}"
        docker push "$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest"