name: Build and Deploy to GCR

on:
  push:
    branches: [ main ]

env:
env:
  PROJECT_ID: ${{ vars.PROJECT_ID }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  REGISTRY: eu.gcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authorize Docker push
      run: gcloud auth configure-docker $REGISTRY

    - name: Build Docker image
      run: |
        docker build \
          --build-arg SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }} \
          --build-arg SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }} \
          --build-arg SPOTIFY_USERNAME=${{ secrets.SPOTIFY_USERNAME }} \
          --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          --tag "$REGISTRY/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }}" \
          --tag "$REGISTRY/$PROJECT_ID/$IMAGE_NAME:latest" \
          .

    - name: Push Docker image
      run: |
        docker push "$REGISTRY/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }}"
        docker push "$REGISTRY/$PROJECT_ID/$IMAGE_NAME:latest"
    
    # Add deployment steps here if needed, e.g., to GKE or Cloud Run
    # - name: Deploy to Cloud Run
    #   uses: google-github-actions/deploy-cloudrun@v1
    #   with:
    #     service: your-service-name
    #     image: ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
    #     region: us-central1
