name: Build and Deploy to GCR

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: your-project-id
  IMAGE_NAME: your-app-name
  REGISTRY: gcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and push Docker image
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        SPOTIFY_USERNAME: ${{ secrets.SPOTIFY_USERNAME }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        gcloud auth configure-docker
        docker build --tag "$REGISTRY/$PROJECT_ID/$IMAGE_NAME:latest" .
        docker push "$REGISTRY/$PROJECT_ID/$IMAGE_NAME:latest"